services:
  nginx:
    container_name: chess-lb
    image: nginx:1.27-alpine
    ports:
      - "8080:8080"
    networks:
      - chess-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    
  redis:
    container_name: redis-chess
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - chess-net
    restart: unless-stopped

networks:
  chess-net:
    driver: bridge